#!/bin/sh

uci delete dhcp.cfg02411c.filterwin2k
uci delete dhcp.cfg02411c.nonegcache

uci set dhcp.cfg02411c.nonwildcard=0
uci set dhcp.cfg02411c.server+=192.168.1.1
uci set dhcp.lan.ra_management=1

uci set dhcp.wlan=dhcp
uci set dhcp.wlan.interface=wlan
uci set dhcp.wlan.leasetime=12h
uci set dhcp.wlan.limit=150
uci set dhcp.wlan.start=100

uci delete network.lan.type

uci set network.wlan=interface
uci set network.wlan.ipaddr=192.168.2.1
uci set network.wlan.netmask=255.255.255.0
uci set network.wlan.proto=static
uci set network.wlan.type=bridge

uci set firewall.cfg1edc81=zone
uci set firewall.cfg1edc81.forward=ACCEPT
uci set firewall.cfg1edc81.input=ACCEPT
uci set firewall.cfg1edc81.name=wlan
uci set firewall.cfg1edc81.network=wlan
uci set firewall.cfg1edc81.output=ACCEPT

uci set firewall.cfg1fad58=forwarding
uci set firewall.cfg1fad58.dest=wan
uci set firewall.cfg1fad58.src=wlan

uci set firewall.cfg04dc81.network=lan

uci set firewall.cfg06dc81.network=wan wan6

uci set wireless.default_radio0.network=lan wlan

uci set wireless.default_radio1.network=lan wlan

uci commit
